<?php

namespace RecipeBundle\Repository;

/**
 * Cat‚gorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat‚gorieRepository extends \Doctrine\ORM\EntityRepository
{
}
